### ISSUE TITLE
USER STORY: Save Artworks

### ISSUE THREAD

**Issue by annieross10** [annieross10/Brushstrokes#4]
As a **registered user**, I can **save my favourite artworks to a collection** so that **I can easily access and edit my preferred pieces**.

**Acceptance Criteria**

- The user interface should enable registered users to save their favourite artworks to a personalised collection.
- Each artwork should have a "Save to Collection" option for registered users.
- Registered users should be able to easily add and remove artworks from their collection.
- A "My Account" section or page should be accessible to registered users, allowing them to view and manage their saved artworks.

**Tasks:**

- [x] Add a "Save to Collection" option for each artwork in the user interface
- [x] Ensure the "Save to Collection" will turn to "Saved to Collection" when clicked
- [x] Ensure that when clicking "Saved to collection" again it will remove the artwork from the Collection and turn back to "Save to Collection"
- [x] Ensure there is an extra prompt asking whether the user wants to remove the artwork.
- [x] Ensure the "Account" section is only accessible to registered users for viewing and managing their own saved artworks.
- [x] Test the funcitonality
